[package]

authors = ["oeed"]
description = "Syslog message formatter and writer, supporting unix sockets, UDP and TCP exporters"
documentation = "https://docs.rs/syslog"
keywords = ["syslog", "logs", "logging"]
license = "MIT"
name = "syslog_esp32"
repository = "https://github.com/oeed/rust-syslog-esp32"
version = "7.0.0"

[dependencies]
esp-idf-svc = "0.51"
log = {version = "0.4.8", features = ["std"]}
time = {version = "0.3.5", features = ["formatting"]}
